### PR TITLE
Updating the install path for OctoEverywhere

### PR DESCRIPTION
**Pull request by QuinnDamerell**
From our discussion on the last PR, I'm updating the install path of the plugin.

### CODE REVIEW

**Comment by Guilouz** [comment]
Merged but needed changes for people already have installed in usr/share folder, they can't uninstall it.

**Comment by Guilouz** [comment]
@QuinnDamerell I think you have made an error for install folder in your install script no ? 

if grep -Fqs "ID=buildroot" /etc/os-release
then
    IS_K1_OS=1
    # On the K1, we always want the path to be /usr/bin
    # /usr/share has very limited space, so we don't want to use it.
    # This is also where the github script installs moonraker and everything.
    HOME="/usr/bin"
fi

Must be :

if grep -Fqs "ID=buildroot" /etc/os-release
then
    IS_K1_OS=1
    # On the K1, we always want the path to be /usr/bin
    # /usr/share has very limited space, so we don't want to use it.
    # This is also where the github script installs moonraker and everything.
    HOME="/usr/data"
fi

**Comment by QuinnDamerell** [comment]
Shoot your right, good catch. I was just trying to run the installer and was running into that. I just fixed it.

**Comment by QuinnDamerell** [comment]
For all users who installed it in either of the past locations, I can query the printers and send them an email with how to correct it.

**Comment by Guilouz** [comment]
> For all users who installed it in either of the past locations, I can query the printers and send them an email with how to correct it.

Yes that's would be good and easier for support.

**Comment by Guilouz** [comment]
@QuinnDamerell Also a question, what is the best way to update octoeverywhere in update manager ? use install.sh or update.sh ?

**Comment by QuinnDamerell** [comment]
Oh, good question. I don't know why I didn't think about adding that. The best way is to call update.sh. It basically just pulls the repo and the calls the ./install script in a special mode.

**Comment by Guilouz** [comment]
> Oh, good question. I don't know why I didn't think about adding that. The best way is to call update.sh. It basically just pulls the repo and the calls the ./install script in a special mode.

Something similar to this no ? :

[update_manager OctoEverywhere]
type: git_repo
path: /usr/data/octoeverywhere
origin: https://github.com/QuinnDamerell/OctoPrint-OctoEverywhere.git
primary_branch: main
install_script: install.sh
is_system_service: False

**Comment by QuinnDamerell** [comment]
Oh yeah. Ideally, if the Moonraker update system is enabled, it would be hooked up in it to enable updates. But the plugin will make that registration in the Moonraker config automatically, it’s included in the -system.cfg file. It always writes the file, so if it’s enabled, it will work. 

The update script is if the user can’t be updated via the Moonraker system. The sonic pad for example has the Moonraker update system disabled. Due to the nature of the plugin and server protocol, keeping things updated is really helpful for me. That why I have the update script, so if I detect a plugin is too old, I can tell the user how to update it easily. 

In your case, I think the Moonraker update system is enabled right? Then OE should show up in it.

**Comment by Guilouz** [comment]
That’s mean if moonraker is in update manager octoeverywhere is updated too?

**Comment by Guilouz** [comment]
@QuinnDamerell Do you have Discord to talk about new script version?

**Comment by QuinnDamerell** [comment]
@Guilouz yes! My handle is Quinninator. I'm always on discord, so it's a great place to chat.

**Pull request merged**
