### PR TITLE
Adding OctoEverywhere Install Support

### PR DESCRIPTION
**Pull request by QuinnDamerell**
I just pushed complete K1 and K1 max support to my master branch, so it's ready for primetime!

I have been updating the docs of my site to refer to this script for installing on the K1, since it can do it all. The user experience of the script is much better than listing commands to run, so thank you!

A quick overview of the OctoEverywhere installer. I have it all set up to run through the ./install script, which installs the required dependencies and creates the virtual environment, and then it kicks off a PY installer to do the full install. The exact process is used for the removal logic, the ./uninstall script calls ./install with a flag, and when the PY installer is started, it does the removal logic.

Please feel free to change anything I have here. I tried to stick to your conventions so it would be minimal work for you. I tested it on my K1 Max, and it works like a charm! 

Let me know if you need anything from me, I'm happy to help.

### CODE REVIEW

**Comment by Guilouz** [comment]
Indentation of install and uninstall sequence are not correct.

**Comment by QuinnDamerell** [comment]
@Guilouz good catches! I adding OctoEverywhere to the info section.

For the indentation, there seems to be a mix of tabs and spaces. I'm not sure what the best approach is, in the last commit I converted the entire file from tab -> spaces. But I can do whatever you want, I can only fix up the places I touched, or convert them all to tabs. Let me know!

**Comment by QuinnDamerell** [comment]
Thank you! If you ever need anything from me regarding OE, please don't hesitate to reach out! (here or on Discord)

**Comment by jrezin** [comment]
would it be possible to move the installation to `/usr/data/`  (like most of the stuff in the helper script)? maybe create a link `/usr/data/` to `/usr/share/` after, if the other path is necessary.
the space available in `/usr/share/` in K1 is _really_ limited...

**Comment by Guilouz** [comment]
Yes it was also my idea to put everything in the usr/data folder @QuinnDamerell What do you think ?

**Comment by QuinnDamerell** [comment]
Good call! I just updated my repo to support the k1 installing to /usr/data and sent a PR to this repo to update the install script. 

Thanks for the callout @jrezin!

**Comment by QuinnDamerell** [comment]
#118 - here's the new PR for reference.

**Pull request merged**
